// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api.proto

package grpc_metrics

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MType string                 `protobuf:"bytes,2,opt,name=m_type,json=mType,proto3" json:"m_type,omitempty"`
	// Types that are valid to be assigned to MetricValue:
	//
	//	*Metric_Delta
	//	*Metric_Value
	MetricValue   isMetric_MetricValue `protobuf_oneof:"metric_value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metric) GetMType() string {
	if x != nil {
		return x.MType
	}
	return ""
}

func (x *Metric) GetMetricValue() isMetric_MetricValue {
	if x != nil {
		return x.MetricValue
	}
	return nil
}

func (x *Metric) GetDelta() int64 {
	if x != nil {
		if x, ok := x.MetricValue.(*Metric_Delta); ok {
			return x.Delta
		}
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		if x, ok := x.MetricValue.(*Metric_Value); ok {
			return x.Value
		}
	}
	return 0
}

type isMetric_MetricValue interface {
	isMetric_MetricValue()
}

type Metric_Delta struct {
	Delta int64 `protobuf:"varint,3,opt,name=delta,proto3,oneof"`
}

type Metric_Value struct {
	Value float64 `protobuf:"fixed64,4,opt,name=value,proto3,oneof"`
}

func (*Metric_Delta) isMetric_MetricValue() {}

func (*Metric_Value) isMetric_MetricValue() {}

type GetMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricRequest) Reset() {
	*x = GetMetricRequest{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricRequest) ProtoMessage() {}

func (x *GetMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricRequest.ProtoReflect.Descriptor instead.
func (*GetMetricRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetMetricRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMetricRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricResponse) Reset() {
	*x = GetMetricResponse{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricResponse) ProtoMessage() {}

func (x *GetMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricResponse.ProtoReflect.Descriptor instead.
func (*GetMetricResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetMetricResponse) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type GetAllMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllMetricsResponse) Reset() {
	*x = GetAllMetricsResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllMetricsResponse) ProtoMessage() {}

func (x *GetAllMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetAllMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllMetricsResponse) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type UpdateMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricRequest) Reset() {
	*x = UpdateMetricRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricRequest) ProtoMessage() {}

func (x *UpdateMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMetricRequest) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type UpdateMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsRequest) Reset() {
	*x = UpdateMetricsRequest{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsRequest) ProtoMessage() {}

func (x *UpdateMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMetricsRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\rMetricsServer\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"o\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06m_type\x18\x02 \x01(\tR\x05mType\x12\x16\n" +
	"\x05delta\x18\x03 \x01(\x03H\x00R\x05delta\x12\x16\n" +
	"\x05value\x18\x04 \x01(\x01H\x00R\x05valueB\x0e\n" +
	"\fmetric_value\"6\n" +
	"\x10GetMetricRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"B\n" +
	"\x11GetMetricResponse\x12-\n" +
	"\x06metric\x18\x01 \x01(\v2\x15.MetricsServer.MetricR\x06metric\"H\n" +
	"\x15GetAllMetricsResponse\x12/\n" +
	"\ametrics\x18\x01 \x03(\v2\x15.MetricsServer.MetricR\ametrics\"D\n" +
	"\x13UpdateMetricRequest\x12-\n" +
	"\x06metric\x18\x01 \x01(\v2\x15.MetricsServer.MetricR\x06metric\"G\n" +
	"\x14UpdateMetricsRequest\x12/\n" +
	"\ametrics\x18\x01 \x03(\v2\x15.MetricsServer.MetricR\ametrics2\xb0\x04\n" +
	"\x0eMetricsService\x12q\n" +
	"\tGetMetric\x12\x1f.MetricsServer.GetMetricRequest\x1a .MetricsServer.GetMetricResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/value/{type}/{id}\x12_\n" +
	"\rGetAllMetrics\x12\x16.google.protobuf.Empty\x1a$.MetricsServer.GetAllMetricsResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/api/v1/\x12\x90\x01\n" +
	"\fUpdateMetric\x12\".MetricsServer.UpdateMetricRequest\x1a\x16.google.protobuf.Empty\"D\x82\xd3\xe4\x93\x02>:\x01*\"9/api/v1/update/{metric.m_type}/{metric.id}/{metric_value}\x12i\n" +
	"\rUpdateMetrics\x12#.MetricsServer.UpdateMetricsRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/updates/\x12L\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/pingB\x12Z\x10pkg/grpc-metricsb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_goTypes = []any{
	(*Metric)(nil),                // 0: MetricsServer.Metric
	(*GetMetricRequest)(nil),      // 1: MetricsServer.GetMetricRequest
	(*GetMetricResponse)(nil),     // 2: MetricsServer.GetMetricResponse
	(*GetAllMetricsResponse)(nil), // 3: MetricsServer.GetAllMetricsResponse
	(*UpdateMetricRequest)(nil),   // 4: MetricsServer.UpdateMetricRequest
	(*UpdateMetricsRequest)(nil),  // 5: MetricsServer.UpdateMetricsRequest
	(*empty.Empty)(nil),           // 6: google.protobuf.Empty
}
var file_api_proto_depIdxs = []int32{
	0, // 0: MetricsServer.GetMetricResponse.metric:type_name -> MetricsServer.Metric
	0, // 1: MetricsServer.GetAllMetricsResponse.metrics:type_name -> MetricsServer.Metric
	0, // 2: MetricsServer.UpdateMetricRequest.metric:type_name -> MetricsServer.Metric
	0, // 3: MetricsServer.UpdateMetricsRequest.metrics:type_name -> MetricsServer.Metric
	1, // 4: MetricsServer.MetricsService.GetMetric:input_type -> MetricsServer.GetMetricRequest
	6, // 5: MetricsServer.MetricsService.GetAllMetrics:input_type -> google.protobuf.Empty
	4, // 6: MetricsServer.MetricsService.UpdateMetric:input_type -> MetricsServer.UpdateMetricRequest
	5, // 7: MetricsServer.MetricsService.UpdateMetrics:input_type -> MetricsServer.UpdateMetricsRequest
	6, // 8: MetricsServer.MetricsService.Ping:input_type -> google.protobuf.Empty
	2, // 9: MetricsServer.MetricsService.GetMetric:output_type -> MetricsServer.GetMetricResponse
	3, // 10: MetricsServer.MetricsService.GetAllMetrics:output_type -> MetricsServer.GetAllMetricsResponse
	6, // 11: MetricsServer.MetricsService.UpdateMetric:output_type -> google.protobuf.Empty
	6, // 12: MetricsServer.MetricsService.UpdateMetrics:output_type -> google.protobuf.Empty
	6, // 13: MetricsServer.MetricsService.Ping:output_type -> google.protobuf.Empty
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_api_proto_msgTypes[0].OneofWrappers = []any{
		(*Metric_Delta)(nil),
		(*Metric_Value)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
